//! Collecting the account password FROM THE USER (dig_ecosystem#1817).
//!
//! Until this module existed, a DIG account's unlock password was generated by the machine and kept in
//! the OS credential store, so "Unlock…" asked for nothing and any code running in the user's session
//! could open the master seed. The sealing crypto was never the weakness — the *secret* was, because
//! there wasn't one the user knew.
//!
//! This module is the one place a password is asked for, and it draws the app's own native input window
//! ([`request_input`](crate::confirm::NativeConfirmer::request_input)) rather than inventing a surface.
//! Two questions are asked, and they are deliberately different:
//!
//! - [`establish_password`] — *choose* a password for an account being created (or re-sealed). Typed
//!   TWICE, because a typo here is unrecoverable: the account would be sealed under characters the user
//!   never intended and could never reproduce.
//! - [`request_password`] — *enter* the password for an account that already exists. Asked once; a wrong
//!   answer costs a failed unlock, not an account.
//!
//! Everything typed lives in [`Zeroizing`] and is never logged, never returned in a `Debug`, and never
//! persisted. A cancelled or undrawable window is NEVER an empty password — see [`PasswordOutcome`].

use zeroize::Zeroizing;

use crate::confirm::{ConfirmDecision, InputOutcome, InputPrompt, NativeConfirmer, NoticePrompt};

/// The shortest account password accepted.
///
/// This guards against a slip (an empty field, one stray character) rather than against an offline
/// cracker — the sealed blob is stretched with Argon2id, and the recovery phrase, not the password, is
/// what makes the account portable. A floor set high enough to be a real brute-force barrier would
/// instead push people toward a password they cannot remember, which for a seal with no reset is a worse
/// failure than a short one.
pub const MIN_PASSWORD_LEN: usize = 10;

/// How many times the user may get it wrong (too short, or the two entries disagreeing) before
/// [`establish_password`] gives up.
///
/// Bounded so a scripted or broken input surface cannot spin forever, and generous enough that a person
/// mistyping twice still gets there.
const MAX_ESTABLISH_ATTEMPTS: usize = 5;

/// What came back from asking for a password.
///
/// The three arms are kept apart for the same reason [`InputOutcome`]'s are: "the user chose not to"
/// and "we could not ask" are different facts, and neither may be silently turned into a password.
pub enum PasswordOutcome {
    /// The user supplied a password meeting [`MIN_PASSWORD_LEN`] (and, for an establishment, typed the
    /// same one twice).
    Provided(Zeroizing<String>),
    /// The user backed out, or ran out of attempts. Nothing may be sealed or unlocked.
    Cancelled,
    /// No input window could be drawn (a headless host, no desktop session). Callers MUST fail closed.
    Unavailable,
}

impl std::fmt::Debug for PasswordOutcome {
    /// Redacts the password. This type carries the secret that opens the master seed, so a derived
    /// `Debug` would put it into any log line, panic message, or test failure that formatted it —
    /// exactly the leak `InputOutcome` already hand-writes its `Debug` to prevent.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Provided(text) => write!(f, "Provided(<{} redacted chars>)", text.len()),
            Self::Cancelled => f.write_str("Cancelled"),
            Self::Unavailable => f.write_str("Unavailable"),
        }
    }
}

/// Ask the user to CHOOSE a password for an account being created or re-sealed.
///
/// The password is typed twice and both entries must match, because nothing downstream can detect a
/// typo: the account would seal successfully under characters the user never meant and would refuse
/// every later unlock. `purpose` names what the password is being set for, so the same window serves
/// first-run setup and the re-seal a migration performs without either pretending to be the other.
///
/// A too-short or mismatched entry is explained and re-asked, up to [`MAX_ESTABLISH_ATTEMPTS`]. A
/// cancellation at ANY point stops immediately — a person backing out of the second field is backing
/// out of setup, not asking to start over.
pub fn establish_password(confirmer: &dyn NativeConfirmer, purpose: &str) -> PasswordOutcome {
    for _ in 0..MAX_ESTABLISH_ATTEMPTS {
        let chosen = match ask(
            confirmer,
            "DIG — Choose your account password",
            purpose,
            &format!(
                "You will be asked for this password whenever DIG needs to unlock your account to \
                 sign something. It is not stored anywhere and nobody can reset it — if you forget \
                 it, your 24-word recovery phrase is the only way back in.\n\n\
                 At least {MIN_PASSWORD_LEN} characters."
            ),
            "New password:",
            "Continue",
        ) {
            Ok(text) => text,
            Err(stop) => return stop,
        };

        if chosen.chars().count() < MIN_PASSWORD_LEN {
            if !explain(
                confirmer,
                "That password is too short.",
                &format!("Please choose one of at least {MIN_PASSWORD_LEN} characters."),
            ) {
                return PasswordOutcome::Unavailable;
            }
            continue;
        }

        let again = match ask(
            confirmer,
            "DIG — Confirm your account password",
            "Type the same password once more.",
            "This second entry is what catches a typo. A password with a typo in it seals your \
             account just as well as the one you meant — and then never opens it again.",
            "Password again:",
            "Set password",
        ) {
            Ok(text) => text,
            Err(stop) => return stop,
        };

        // Compare the whole strings: this is a user re-typing their own choice, not an attacker
        // probing a secret, so there is no oracle to leak and nothing to gain from a constant-time
        // compare here.
        if *chosen == *again {
            return PasswordOutcome::Provided(chosen);
        }
        if !explain(
            confirmer,
            "Those two passwords are not the same.",
            "Nothing has been changed. Please type it again, twice.",
        ) {
            return PasswordOutcome::Unavailable;
        }
    }
    PasswordOutcome::Cancelled
}

/// Ask the user for the password to an account that ALREADY exists.
///
/// Asked once and not re-validated against [`MIN_PASSWORD_LEN`]: the account is already sealed under
/// whatever it is sealed under, and rejecting a short entry here would only refuse to TRY a password
/// that might well be right. A wrong answer fails the unlock, which is the honest place for it to fail.
///
/// `reason` says why the account is being opened right now (a signature, a reveal, a plain unlock), so
/// the window can never be mistaken for an unprompted demand for a secret.
pub fn request_password(confirmer: &dyn NativeConfirmer, reason: &str) -> PasswordOutcome {
    match ask(
        confirmer,
        "DIG — Unlock your account",
        reason,
        "Your DIG account is locked. Enter the password you chose when you set it up.\n\n\
         DIG will never ask for your 24 words here.",
        "Password:",
        "Unlock",
    ) {
        Ok(text) => PasswordOutcome::Provided(text),
        Err(stop) => stop,
    }
}

/// Draw one masked input window and return what was typed, or the [`PasswordOutcome`] that ends the
/// whole flow.
///
/// The `Err` arm is deliberately the OUTCOME rather than an error type: a cancellation and an undrawable
/// window are both terminal for the caller, and returning them already-shaped stops each call site
/// re-deriving that mapping (and getting it wrong in one place).
fn ask(
    confirmer: &dyn NativeConfirmer,
    title: &str,
    heading: &str,
    body: &str,
    field_label: &str,
    submit: &'static str,
) -> Result<Zeroizing<String>, PasswordOutcome> {
    match confirmer.request_input(&InputPrompt {
        title,
        heading,
        body,
        field_label,
        submit,
        // A password is short enough to retype and is the one secret a shoulder-surfer gets no second
        // chance at, so it is masked AND deliberately un-revealable — unlike the 24 words, which cannot
        // be checked at all if they are typed blind (`SPEC.md` §3.1d).
        masked: true,
        revealable: false,
    }) {
        InputOutcome::Provided(text) => Ok(text),
        InputOutcome::Cancelled => Err(PasswordOutcome::Cancelled),
        InputOutcome::Unavailable => Err(PasswordOutcome::Unavailable),
    }
}

/// Tell the user why their entry was not accepted. Returns whether the message reached the screen — a
/// host that cannot draw a notice cannot usefully be re-asked either, so the caller stops.
fn explain(confirmer: &dyn NativeConfirmer, heading: &str, body: &str) -> bool {
    !matches!(
        confirmer.show_notice(&NoticePrompt {
            title: "DIG — Password not accepted",
            heading,
            body,
            acknowledge: "Try again",
        }),
        ConfirmDecision::Unavailable
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::confirm::{ConnectPrompt, PairPrompt, SignPrompt};
    use std::sync::Mutex;

    /// A [`NativeConfirmer`] double that plays a SCRIPT of input outcomes in order and records every
    /// prompt it was shown.
    ///
    /// A double that could only return one fixed answer could not express the two failures this module
    /// exists to handle — a mismatch between the first and second entry, and a short entry followed by
    /// a good one. Both are multi-answer facts, so the double has to be able to answer differently each
    /// time it is asked.
    struct ScriptedInput {
        answers: Mutex<std::collections::VecDeque<InputOutcome>>,
        /// Every `(field_label, masked)` pair asked for, in order.
        asked: Mutex<Vec<(String, bool)>>,
        /// The heading of each notice shown, in order.
        notices: Mutex<Vec<String>>,
        /// What a notice reports — `Unavailable` models a host that cannot draw one.
        notice_decision: ConfirmDecision,
    }

    impl ScriptedInput {
        fn new(answers: Vec<InputOutcome>) -> Self {
            Self {
                answers: Mutex::new(answers.into()),
                asked: Mutex::new(Vec::new()),
                notices: Mutex::new(Vec::new()),
                notice_decision: ConfirmDecision::Approve,
            }
        }

        fn typing(entries: &[&str]) -> Self {
            Self::new(
                entries
                    .iter()
                    .map(|t| InputOutcome::Provided(Zeroizing::new((*t).to_string())))
                    .collect(),
            )
        }

        fn asked_count(&self) -> usize {
            self.asked.lock().unwrap().len()
        }
    }

    impl NativeConfirmer for ScriptedInput {
        fn confirm_pair(&self, _p: &PairPrompt<'_>) -> ConfirmDecision {
            unreachable!("collecting a password never pairs")
        }
        fn confirm_connect(&self, _p: &ConnectPrompt<'_>) -> ConfirmDecision {
            unreachable!("collecting a password never connects")
        }
        fn confirm_sign(&self, _p: &SignPrompt<'_>) -> ConfirmDecision {
            unreachable!("collecting a password never signs")
        }
        fn show_notice(&self, prompt: &NoticePrompt<'_>) -> ConfirmDecision {
            self.notices
                .lock()
                .unwrap()
                .push(prompt.heading.to_string());
            self.notice_decision
        }
        fn request_input(&self, prompt: &InputPrompt<'_>) -> InputOutcome {
            self.asked
                .lock()
                .unwrap()
                .push((prompt.field_label.to_string(), prompt.masked));
            self.answers
                .lock()
                .unwrap()
                .pop_front()
                .unwrap_or(InputOutcome::Cancelled)
        }
    }

    /// A password comfortably over the floor, and NOT a plausible real one — the tests assert
    /// plumbing, so the value only has to be distinguishable and long enough.
    const GOOD: &str = "correct-horse-battery";
    /// A DIFFERENT password of the same shape, so a mismatch test cannot pass by both entries being
    /// the same value under two names.
    const OTHER: &str = "staple-tourniquet-42";

    fn provided(outcome: PasswordOutcome) -> String {
        match outcome {
            PasswordOutcome::Provided(text) => text.to_string(),
            other => panic!("expected a password, got {other:?}"),
        }
    }

    #[test]
    fn establishing_asks_twice_and_returns_the_agreed_password() {
        let confirmer = ScriptedInput::typing(&[GOOD, GOOD]);
        let outcome = establish_password(&confirmer, "Set a password for your new DIG account.");

        assert_eq!(provided(outcome), GOOD);
        // Twice, not once: a single-entry establishment would pass an "it returns what was typed"
        // assertion identically, so the COUNT is what pins the confirmation round.
        assert_eq!(confirmer.asked_count(), 2);
        assert!(
            confirmer.notices.lock().unwrap().is_empty(),
            "a clean first attempt explains nothing"
        );
    }

    /// Every password window must be masked. Asserted on the recorded prompts rather than trusted,
    /// because masking is a one-field property that is easy to lose in a later edit.
    #[test]
    fn every_password_field_is_masked() {
        let confirmer = ScriptedInput::typing(&[GOOD, GOOD]);
        establish_password(&confirmer, "purpose");
        let unlock = ScriptedInput::typing(&[GOOD]);
        request_password(&unlock, "reason");

        for asked in confirmer
            .asked
            .lock()
            .unwrap()
            .iter()
            .chain(unlock.asked.lock().unwrap().iter())
        {
            assert!(asked.1, "the {} field must be masked", asked.0);
        }
    }

    /// The confirmation round has to be load-bearing: two DIFFERENT entries must not establish
    /// anything, and the user must be told why.
    #[test]
    fn two_different_entries_do_not_establish_a_password() {
        // Third and fourth entries agree, so the flow recovers — which also proves the mismatch was a
        // re-ask rather than a silent acceptance of either value.
        let confirmer = ScriptedInput::typing(&[GOOD, OTHER, OTHER, OTHER]);

        let outcome = establish_password(&confirmer, "purpose");

        assert_eq!(
            provided(outcome),
            OTHER,
            "the password that survives must be the one typed twice in agreement"
        );
        assert_eq!(
            confirmer.asked_count(),
            4,
            "the mismatch forced a full re-ask"
        );
        assert_eq!(
            confirmer.notices.lock().unwrap().len(),
            1,
            "the user is told the two did not match"
        );
    }

    /// A password under the floor is refused BEFORE the confirmation round — asking someone to confirm
    /// an entry that is about to be rejected wastes the one thing the second field is for.
    #[test]
    fn a_too_short_password_is_refused_and_re_asked() {
        let short = "a".repeat(MIN_PASSWORD_LEN - 1);
        let confirmer = ScriptedInput::typing(&[&short, GOOD, GOOD]);

        assert_eq!(provided(establish_password(&confirmer, "purpose")), GOOD);
        assert_eq!(
            confirmer.asked_count(),
            3,
            "the short entry cost ONE window, not a confirmation round as well"
        );
    }

    /// The floor is pinned from BOTH sides. A test that only proves "one under fails" cannot tell
    /// `MIN_PASSWORD_LEN` from `MIN_PASSWORD_LEN + 1`.
    #[test]
    fn a_password_of_exactly_the_minimum_length_is_accepted() {
        let at_bound = "b".repeat(MIN_PASSWORD_LEN);
        let confirmer = ScriptedInput::typing(&[&at_bound, &at_bound]);

        assert_eq!(
            provided(establish_password(&confirmer, "purpose")),
            at_bound
        );
        assert_eq!(
            confirmer.asked_count(),
            2,
            "at the bound nothing is re-asked"
        );
    }

    /// The length floor counts CHARACTERS, not bytes: a 10-character passphrase in a non-Latin script
    /// is well over the byte floor and would be accepted by a byte count, but a 9-character one would
    /// ALSO be accepted — so a byte count silently lowers the bound for most of the world.
    #[test]
    fn the_length_floor_counts_characters_not_bytes() {
        // Nine multi-byte characters: 27 bytes, comfortably over a byte-counted floor, and one
        // character UNDER the real one.
        let nine_chars = "パスワードテスト用語".chars().take(9).collect::<String>();
        assert!(
            nine_chars.len() > MIN_PASSWORD_LEN,
            "the fixture must pass a byte count"
        );
        let confirmer = ScriptedInput::typing(&[&nine_chars, GOOD, GOOD]);

        assert_eq!(provided(establish_password(&confirmer, "purpose")), GOOD);
        assert_eq!(
            confirmer.notices.lock().unwrap().len(),
            1,
            "the nine-character entry must have been refused as too short"
        );
    }

    #[test]
    fn cancelling_the_first_field_establishes_nothing_and_stops() {
        let confirmer = ScriptedInput::new(vec![InputOutcome::Cancelled]);
        assert!(matches!(
            establish_password(&confirmer, "purpose"),
            PasswordOutcome::Cancelled
        ));
        assert_eq!(confirmer.asked_count(), 1, "a cancellation is not retried");
    }

    /// Backing out of the SECOND field is backing out of setup, not asking to start over. Retrying
    /// there would trap someone who has decided to stop.
    #[test]
    fn cancelling_the_confirmation_field_stops_immediately() {
        let confirmer = ScriptedInput::new(vec![
            InputOutcome::Provided(Zeroizing::new(GOOD.into())),
            InputOutcome::Cancelled,
        ]);
        assert!(matches!(
            establish_password(&confirmer, "purpose"),
            PasswordOutcome::Cancelled
        ));
        assert_eq!(confirmer.asked_count(), 2);
    }

    /// A host that cannot draw the window reports so — it must never come back as an empty password,
    /// which would seal an account under nothing at all.
    #[test]
    fn an_undrawable_window_fails_closed_on_both_questions() {
        assert!(matches!(
            establish_password(&ScriptedInput::new(vec![InputOutcome::Unavailable]), "p"),
            PasswordOutcome::Unavailable
        ));
        assert!(matches!(
            request_password(&ScriptedInput::new(vec![InputOutcome::Unavailable]), "r"),
            PasswordOutcome::Unavailable
        ));
    }

    /// A host that can draw an input window but not a NOTICE cannot explain a rejection, so it stops
    /// rather than re-asking a question whose refusal the user would never see.
    #[test]
    fn a_rejection_that_cannot_be_explained_stops_the_flow() {
        let mut confirmer = ScriptedInput::typing(&["short", GOOD, GOOD]);
        confirmer.notice_decision = ConfirmDecision::Unavailable;

        assert!(matches!(
            establish_password(&confirmer, "purpose"),
            PasswordOutcome::Unavailable
        ));
    }

    /// Repeated mismatches give up rather than looping for ever — an input surface stuck returning the
    /// same disagreeing pair must not spin.
    #[test]
    fn endless_mismatches_give_up() {
        let mut answers = Vec::new();
        for _ in 0..(MAX_ESTABLISH_ATTEMPTS * 2 + 2) {
            answers.push(InputOutcome::Provided(Zeroizing::new(GOOD.into())));
            answers.push(InputOutcome::Provided(Zeroizing::new(OTHER.into())));
        }
        let confirmer = ScriptedInput::new(answers);

        assert!(matches!(
            establish_password(&confirmer, "purpose"),
            PasswordOutcome::Cancelled
        ));
        assert_eq!(
            confirmer.asked_count(),
            MAX_ESTABLISH_ATTEMPTS * 2,
            "exactly the bounded number of attempts, then it stops"
        );
    }

    /// Unlocking asks ONCE and relays what was typed verbatim — including a short one, which is not
    /// this function's to judge (the seal decides).
    #[test]
    fn requesting_an_existing_password_asks_once_and_relays_it() {
        let confirmer = ScriptedInput::typing(&["x"]);
        assert_eq!(provided(request_password(&confirmer, "to sign")), "x");
        assert_eq!(confirmer.asked_count(), 1);
        assert!(confirmer.notices.lock().unwrap().is_empty());
    }

    #[test]
    fn cancelling_an_unlock_yields_no_password() {
        let confirmer = ScriptedInput::new(vec![InputOutcome::Cancelled]);
        assert!(matches!(
            request_password(&confirmer, "to sign"),
            PasswordOutcome::Cancelled
        ));
    }

    /// The `Debug` impl must not print the secret — this type is formatted in test failures and could
    /// otherwise carry a live password into a log.
    #[test]
    fn debug_redacts_the_password() {
        let rendered = format!(
            "{:?}",
            PasswordOutcome::Provided(Zeroizing::new(GOOD.to_string()))
        );
        assert!(!rendered.contains(GOOD), "the password leaked: {rendered}");
        assert!(rendered.contains("redacted"));
    }
}
