//! Parsing the `wc:` pairing string a person pastes into the tray (WalletConnect v2, Sage parity).
//!
//! The string is the ONLY thing WalletConnect gives a wallet to start from, and everything that
//! follows — which relay topic to listen on, which key decrypts the first envelope — is read out of
//! it. So this parser is a trust boundary, not a convenience: the text arrives from a person's
//! clipboard, which is to say from whatever website last wrote to it.
//!
//! # Why this refuses rather than repairs
//!
//! A pairing string that is nearly right is not nearly safe. A truncated `symKey` silently padded to
//! 32 bytes would produce a key an attacker can guess the tail of; a missing `@2` accepted as v2
//! would let a v1 string — a protocol with a different and weaker key exchange — reach v2 code. Every
//! field is therefore checked for exactly what the spec says it is, and anything else is a named
//! [`UriError`] the tray can show a person. There is no lenient mode.

use std::fmt;

/// A parsed WalletConnect v2 pairing URI.
///
/// Holds only what the pairing needs. `relay_protocol` is retained rather than asserted away because
/// the relay handshake sends it back, and a wallet that rewrote it to `irn` would be lying to the
/// relay about what it was asked for.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WcUri {
    /// The pairing topic: 32 bytes, lowercase hex. The relay subscription starts here.
    pub topic: String,
    /// The symmetric key the first envelope on `topic` is sealed under.
    pub sym_key: [u8; 32],
    /// The relay protocol the dapp asked for. `irn` in every deployment today.
    pub relay_protocol: String,
    /// The dapp's own expiry for the pairing, as a unix timestamp, when it supplied one.
    pub expiry_timestamp: Option<u64>,
}

/// Why a pasted string is not a usable pairing URI.
///
/// One variant per distinguishable cause, because the tray shows these to a person and "invalid
/// WalletConnect URI" tells them nothing about whether they mis-copied or their wallet is too old.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UriError {
    /// The text does not begin `wc:`. Almost always a partial copy or the wrong clipboard entry.
    NotWalletConnect,
    /// A `wc:` string of a version this wallet does not speak, carrying the version it asked for.
    ///
    /// Separate from [`Malformed`](Self::Malformed) on purpose: v1 strings are still generated by old
    /// dapps, and a person holding one needs to be told the dapp is out of date rather than that they
    /// typed it wrong.
    UnsupportedVersion(String),
    /// Structurally wrong: no `@`, no query string, an unparsable field.
    Malformed(&'static str),
    /// A required query parameter is absent.
    MissingParam(&'static str),
    /// The pairing topic is not 32 bytes of lowercase hex.
    BadTopic,
    /// `symKey` is not 32 bytes of hex.
    BadSymKey,
}

impl fmt::Display for UriError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NotWalletConnect => {
                write!(
                    f,
                    "that is not a WalletConnect link - it should start with \"wc:\""
                )
            }
            Self::UnsupportedVersion(v) => write!(
                f,
                "that link uses WalletConnect version {v}, and DIG speaks version 2 - the app you \
                 are connecting needs an update"
            ),
            Self::Malformed(what) => write!(f, "that WalletConnect link is incomplete: {what}"),
            Self::MissingParam(p) => {
                write!(f, "that WalletConnect link is missing its \"{p}\" value")
            }
            Self::BadTopic => write!(f, "that WalletConnect link's topic is not readable"),
            Self::BadSymKey => write!(f, "that WalletConnect link's key is not readable"),
        }
    }
}

impl std::error::Error for UriError {}

/// The one WalletConnect version this wallet speaks. Sage speaks the same one and only this one.
const SUPPORTED_VERSION: &str = "2";

/// Bytes in a topic and in a symmetric key. Both are sha256-sized, and neither is a coincidence: the
/// topic IS a sha256 and the key feeds ChaCha20-Poly1305, which takes 32 bytes.
const KEY_LEN: usize = 32;

impl WcUri {
    /// Read a pasted pairing string.
    ///
    /// Surrounding whitespace is trimmed, because a clipboard round-trip through a chat window adds
    /// it and refusing on that would be a puzzle rather than a protection. Nothing else is repaired.
    pub fn parse(raw: &str) -> Result<Self, UriError> {
        let raw = raw.trim();
        let rest = raw.strip_prefix("wc:").ok_or(UriError::NotWalletConnect)?;

        let (topic_and_version, query) = rest
            .split_once('?')
            .ok_or(UriError::Malformed("it carries no relay information"))?;
        let (topic, version) = topic_and_version
            .split_once('@')
            .ok_or(UriError::Malformed("it names no protocol version"))?;

        if version != SUPPORTED_VERSION {
            return Err(UriError::UnsupportedVersion(version.to_string()));
        }
        if !is_hex_32(topic) {
            return Err(UriError::BadTopic);
        }

        let mut relay_protocol = None;
        let mut sym_key_hex = None;
        let mut expiry_timestamp = None;
        for (key, value) in query.split('&').filter_map(|p| p.split_once('=')) {
            match key {
                "relay-protocol" => relay_protocol = Some(value.to_string()),
                "symKey" => sym_key_hex = Some(value),
                // A malformed expiry is dropped rather than fatal: it is the dapp's hint about when
                // it will stop waiting, and a pairing whose hint is unreadable is still pairable.
                // The wallet's own expiry, which is the one that matters, is set on settle.
                "expiryTimestamp" => expiry_timestamp = value.parse::<u64>().ok(),
                _ => {}
            }
        }

        let relay_protocol = relay_protocol.ok_or(UriError::MissingParam("relay-protocol"))?;
        let sym_key_hex = sym_key_hex.ok_or(UriError::MissingParam("symKey"))?;
        let sym_key = parse_key(sym_key_hex).ok_or(UriError::BadSymKey)?;

        Ok(Self {
            topic: topic.to_string(),
            sym_key,
            relay_protocol,
            expiry_timestamp,
        })
    }
}

/// Whether `s` is exactly 32 bytes written as lowercase hex.
///
/// Lowercase specifically. A topic is compared as a STRING against what the relay echoes back, so
/// accepting mixed case here would produce a subscription whose acknowledgements never match.
fn is_hex_32(s: &str) -> bool {
    s.len() == KEY_LEN * 2
        && s.bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

/// Decode 32 bytes of hex, in either case.
///
/// Case-insensitive unlike the topic, because a key is only ever compared as BYTES — the string form
/// never leaves this function, so its case cannot desynchronise anything.
fn parse_key(hex_str: &str) -> Option<[u8; KEY_LEN]> {
    if hex_str.len() != KEY_LEN * 2 {
        return None;
    }
    let mut out = [0u8; KEY_LEN];
    hex::decode_to_slice(hex_str, &mut out).ok()?;
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A well-formed v2 pairing string, as `@walletconnect/sign-client` emits one.
    fn valid() -> String {
        format!(
            "wc:{}@2?relay-protocol=irn&symKey={}",
            "a".repeat(64),
            "b".repeat(64)
        )
    }

    #[test]
    fn parses_a_well_formed_v2_uri() {
        let uri = WcUri::parse(&valid()).expect("valid uri");
        assert_eq!(uri.topic, "a".repeat(64));
        assert_eq!(uri.sym_key, [0xbb; 32]);
        assert_eq!(uri.relay_protocol, "irn");
        assert_eq!(uri.expiry_timestamp, None);
    }

    #[test]
    fn reads_an_optional_expiry() {
        let uri = WcUri::parse(&format!("{}&expiryTimestamp=1799999999", valid())).unwrap();
        assert_eq!(uri.expiry_timestamp, Some(1_799_999_999));
    }

    #[test]
    fn an_unreadable_expiry_does_not_fail_the_pairing() {
        let uri = WcUri::parse(&format!("{}&expiryTimestamp=soon", valid())).unwrap();
        assert_eq!(uri.expiry_timestamp, None);
    }

    #[test]
    fn tolerates_clipboard_whitespace() {
        assert!(WcUri::parse(&format!("  {}\n", valid())).is_ok());
    }

    #[test]
    fn rejects_a_string_that_is_not_walletconnect() {
        assert_eq!(
            WcUri::parse("https://example.com"),
            Err(UriError::NotWalletConnect)
        );
    }

    /// v1 is the case this distinction exists for: the string is a real WalletConnect URI, so the
    /// person did nothing wrong, and the message has to say the dapp is old rather than blame them.
    #[test]
    fn names_the_version_of_a_v1_string() {
        let v1 = format!(
            "wc:{}@1?bridge=https%3A%2F%2Fb.bridge.walletconnect.org&key={}",
            "a".repeat(64),
            "b".repeat(64)
        );
        assert_eq!(
            WcUri::parse(&v1),
            Err(UriError::UnsupportedVersion("1".into()))
        );
    }

    /// The truncation case, stated as its own test because a lenient parser that zero-padded here
    /// would hand ChaCha20 a key whose last bytes an attacker knows.
    #[test]
    fn refuses_a_truncated_sym_key_rather_than_padding_it() {
        let short = format!(
            "wc:{}@2?relay-protocol=irn&symKey={}",
            "a".repeat(64),
            "b".repeat(40)
        );
        assert_eq!(WcUri::parse(&short), Err(UriError::BadSymKey));
    }

    /// An OVER-long key is the other side of the same bound: a parser that took the first 32 bytes
    /// and ignored the rest would accept a key the dapp never agreed to.
    #[test]
    fn refuses_an_over_long_sym_key() {
        let long = format!(
            "wc:{}@2?relay-protocol=irn&symKey={}",
            "a".repeat(64),
            "b".repeat(66)
        );
        assert_eq!(WcUri::parse(&long), Err(UriError::BadSymKey));
    }

    #[test]
    fn refuses_a_non_hex_sym_key_of_the_right_length() {
        let bad = format!(
            "wc:{}@2?relay-protocol=irn&symKey={}",
            "a".repeat(64),
            "z".repeat(64)
        );
        assert_eq!(WcUri::parse(&bad), Err(UriError::BadSymKey));
    }

    #[test]
    fn refuses_a_topic_that_is_not_thirty_two_bytes() {
        let bad = format!(
            "wc:{}@2?relay-protocol=irn&symKey={}",
            "a".repeat(60),
            "b".repeat(64)
        );
        assert_eq!(WcUri::parse(&bad), Err(UriError::BadTopic));
    }

    /// Uppercase is rejected for a reason worth pinning: the topic is string-compared against the
    /// relay's echo, so a case-folded one subscribes to something whose replies never match.
    #[test]
    fn refuses_an_uppercase_topic() {
        let bad = format!(
            "wc:{}@2?relay-protocol=irn&symKey={}",
            "A".repeat(64),
            "b".repeat(64)
        );
        assert_eq!(WcUri::parse(&bad), Err(UriError::BadTopic));
    }

    #[test]
    fn reports_a_missing_relay_protocol_by_name() {
        let bad = format!("wc:{}@2?symKey={}", "a".repeat(64), "b".repeat(64));
        assert_eq!(
            WcUri::parse(&bad),
            Err(UriError::MissingParam("relay-protocol"))
        );
    }

    #[test]
    fn reports_a_missing_sym_key_by_name() {
        let bad = format!("wc:{}@2?relay-protocol=irn", "a".repeat(64));
        assert_eq!(WcUri::parse(&bad), Err(UriError::MissingParam("symKey")));
    }

    #[test]
    fn reports_a_missing_query_string() {
        let bad = format!("wc:{}@2", "a".repeat(64));
        assert!(matches!(WcUri::parse(&bad), Err(UriError::Malformed(_))));
    }

    #[test]
    fn reports_a_missing_version() {
        let bad = format!("wc:{}?relay-protocol=irn", "a".repeat(64));
        assert!(matches!(WcUri::parse(&bad), Err(UriError::Malformed(_))));
    }

    /// Every message a person can be shown names WalletConnect or what to do, never a code.
    #[test]
    fn every_error_renders_a_sentence_a_person_can_act_on() {
        let all = [
            UriError::NotWalletConnect,
            UriError::UnsupportedVersion("1".into()),
            UriError::Malformed("it names no protocol version"),
            UriError::MissingParam("symKey"),
            UriError::BadTopic,
            UriError::BadSymKey,
        ];
        for e in all {
            let rendered = e.to_string();
            assert!(rendered.len() > 20, "terse message: {rendered}");
            assert!(
                rendered.chars().next().is_some_and(|c| c.is_lowercase()),
                "message should read as a clause: {rendered}"
            );
        }
    }
}
